### ISSUE TITLE
Not working with node 8

### ISSUE THREAD

**Issue by Vehmloewff** [jonschlinkert/write#9]
When I call the `write` function and give it a directory that doesn't exist, I get this error.

```
Error: ENOENT: no such file or directory, open '<project_dir>/<directory_that_doesn't_exist>/<file>'
```

node version: `8.17.0`
write version: `2.0.0`

**Suggestion**

Because node 8 does not support the recursive option (used [here](https://github.com/jonschlinkert/write/blob/master/index.js#L55)) you could use something like [sindresorhus/make-dir](https://github.com/sindresorhus/make-dir) which only uses the recursive option if the node version is `>=10.12.0` ([sindresorhus/make-dir/blob/master/index.js#L12](https://github.com/sindresorhus/make-dir/blob/master/index.js#L12)).

**Comment by utsavkapoor** [comment]
I am also facing the same issue. Would really appreciate if this can be implemented

**Comment by doowb** [comment]
In the [Install](https://github.com/jonschlinkert/write#install) section of the README.md it says that this library requires `Node.js >= 10`.

**Comment by utsavkapoor** [comment]
@doowb - I am currently using 10.11.0 and facing the same issue

**Comment by doowb** [comment]
Okay, then I believe that this only requires a patch bump to `2.0.1` with a bump in the required Node.js version specified in the README.md and in the `package.json` `engines` property. 

Since the library was intentionally bumped to `2.0.0` to be able to bump the Node.js version and make use of the `recursive` option on `fs.mkdir`, I think that's all that's necessary.
